site_name: Truffle Suite
site_dir: site
theme:
  name: 'material'
  custom_dir: 'custom_theme/'
  logo: /assets/logo.png
  favicon: /assets/favicon-32x32.png  
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: chocolatey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: "Open Sans"
    code: "Open Sans"
  features:
    - navigation.tabs
  language: en
google_analytics:
  - UA-262533-X
  - auto
copyright: Copyright &copy; 2016 - 2021 ConsenSys Software Inc.
extra:
  generator: false
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/trufflesuite
    name: Twitter
  - icon: fontawesome/brands/github
    link: https://github.com/trufflesuite
    name: Github
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/trufflesuite
    name: LinkedIn
  rebuild: false    
extra_css:
  - /assets/stylesheets/bootstrap.min.css
  - /assets/stylesheets/extra.css
plugins:
  - search
  - awesome-pages
  - macros:
      module_name: main